### ISSUE TITLE
Migration doc from 11.8.6 to 12.0.1

### ISSUE THREAD

**Issue by jbalatero** [Seikho/evtstore#21]
Hi, thank you for this library. I would like to migrate it to the latest but I'm not sure if there's any documentation.

**Comment by Seikho** [comment]
Heya, this is the only breaking change from v11 to v12:
```
Note: createDomain will be migrating to createDomainV2 in version 11.x The createDomainV2 API solves circular reference issues when importing aggregates. The original createDomain will be available as createDomainV1 from 11.x onwards.
```

So you should only need to update `.createDomain(...)` calls. I can't actually recall what changed about the function signature if anything at all.

**Comment by jbalatero** [comment]
Thank you for the quick response.
